import type { SuperviseeFormValues, SupervisorFormValues } from './schema'

export const supervisorDefaultValues: Partial<SupervisorFormValues> = {
  fullName: '',
  email: '',
  password: '',
  contactNumber: '',
  city: '',
  state: '',
  zipcode: '',
  occupationId: '',
  specialtyId: '',
  licenseType: '',
  licenseNumber: '',
  licenseExpiration: '',
  npiNumber: '',
  certifications: [],
  yearsOfExperience: '',
  stateOfLicensure: [],
  patientPopulation: [],
  supervisionFormat: 'virtual',
  availability: '',
  acceptingNewSupervisees: true,
  professionalSummary: '',
  describeYourself: '',
  supervisionFeeType: 'HOURLY',
  supervisionFeeAmount: 0,
  website: '',
  agreedToPost: false,
  agreedToTerms: false,
}

export const superviseeDefaultValues: Partial<SuperviseeFormValues> = {
  fullName: '',
  email: '',
  password: '',
  contactNumber: '',
  city: '',
  state: '',
  zipcode: '',
  occupationId: '',
  stateOfLicensure: [],
  stateTheyAreLookingIn: '',
  typeOfSupervisor: '',
  howSoon: '',
  preferredFormat: 'virtual',
  feeType: 'per-session',
  budgetRange: '',
  availability: '',
  description: '',
  agreedToPost: false,
  agreedToTerms: false,
}
