import type { SelectOption } from '@/lib/api/options'

import type { SupervisorSearchResult } from './types'

/** Mock occupation options for demo — aligns with mock supervisor license types */
export const MOCK_OCCUPATION_OPTIONS: SelectOption[] = [
  { label: 'Physical Therapist', value: 'physical_therapist' },
  { label: 'Licensed Clinical Social Worker', value: 'lcsw' },
  { label: 'Occupational Therapist', value: 'occupational_therapist' },
  { label: 'Licensed Marriage & Family Therapist', value: 'lmft' },
  { label: 'Licensed Psychologist', value: 'psychologist' },
]

/** Mock specialty options by occupation ID — for demo purposes */
export const MOCK_SPECIALTIES_BY_OCCUPATION: Record<string, SelectOption[]> = {
  physical_therapist: [
    { label: 'Orthopedics', value: 'orthopedics' },
    { label: 'Sports Rehab', value: 'sports_rehab' },
    { label: 'Adults', value: 'adults' },
    { label: 'Post-Surgical', value: 'post_surgical' },
  ],
  lcsw: [
    { label: 'Trauma-Informed', value: 'trauma_informed' },
    { label: 'Anxiety & Depression', value: 'anxiety_depression' },
    { label: 'CBT', value: 'cbt' },
    { label: 'DBT', value: 'dbt' },
  ],
  occupational_therapist: [
    { label: 'Pediatrics', value: 'pediatrics' },
    { label: 'Sensory Integration', value: 'sensory_integration' },
    { label: 'School-Based', value: 'school_based' },
    { label: 'Family-Centered', value: 'family_centered' },
  ],
  lmft: [
    { label: 'Couples Therapy', value: 'couples_therapy' },
    { label: 'Family Systems', value: 'family_systems' },
    { label: 'Cultural Humility', value: 'cultural_humility' },
    { label: 'Gottman Method', value: 'gottman_method' },
  ],
  psychologist: [
    { label: 'Neuropsychology', value: 'neuropsychology' },
    { label: 'Assessment', value: 'assessment' },
    { label: 'Community Mental Health', value: 'community_mental_health' },
    { label: 'Multicultural', value: 'multicultural' },
  ],
}

export const MOCK_SUPERVISORS: SupervisorSearchResult[] = [
  {
    id: '1',
    fullName: 'Dr. Sarah Chen, PT, DPT',
    credentials: 'PT, DPT',
    licenseType: 'Licensed Physical Therapist',
    supervisorType: 'Clinical Supervisor',
    yearsOfExperience: '12',
    city: 'New York',
    state: 'NY',
    location: 'New York, NY',
    licenseNumber: 'NY-PT-88241',
    licenseState: 'NY',
    formats: ['VIRTUAL', 'HYBRID'],
    accepting: true,
    bio: 'Specializing in orthopedic and sports rehabilitation with extensive experience supervising new graduates. I focus on evidence-based practice and help supervisees develop strong clinical reasoning and case conceptualization skills for outpatient settings.',
    specialties: ['Orthopedics', 'Sports Rehab', 'Adults', 'Post-Surgical'],
    patientPopulation: ['Adults', 'Seniors'],
    initials: 'SC',
    avatarColor: 'bg-[#006d36]',
  },
  {
    id: '2',
    fullName: 'Marcus Williams, LCSW',
    credentials: 'LCSW',
    licenseType: 'Licensed Clinical Social Worker',
    supervisorType: 'Supervisor',
    yearsOfExperience: '8',
    city: 'Chicago',
    state: 'IL',
    location: 'Chicago, IL',
    licenseNumber: 'IL-LCSW-44519',
    licenseState: 'IL',
    formats: ['VIRTUAL'],
    accepting: true,
    bio: 'I work primarily with adults navigating trauma, anxiety, and life transitions. My supervision style is collaborative and reflective, guiding supervisees to build confidence in direct practice and case conceptualization within community mental health.',
    specialties: ['Trauma-Informed', 'Anxiety & Depression', 'CBT', 'DBT'],
    patientPopulation: ['Adults'],
    initials: 'MW',
    avatarColor: 'bg-[#2563eb]',
  },
  {
    id: '3',
    fullName: 'Dr. Priya Nair, OTD, OTR/L',
    credentials: 'OTD, OTR/L',
    licenseType: 'Occupational Therapist',
    supervisorType: 'Clinical Supervisor',
    yearsOfExperience: '15',
    city: 'Austin',
    state: 'TX',
    location: 'Austin, TX',
    licenseNumber: 'TX-OT-30127',
    licenseState: 'TX',
    formats: ['HYBRID', 'IN_PERSON'],
    accepting: true,
    bio: 'Experienced in pediatric and school-based OT settings. I supervise new clinicians through a strengths-based lens with a focus on sensory integration, functional adaptations, and family-centered care across diverse cultural backgrounds.',
    specialties: ['Pediatrics', 'Sensory Integration', 'School-Based', 'Family-Centered'],
    patientPopulation: ['Children', 'Adolescents'],
    initials: 'PN',
    avatarColor: 'bg-[#7c3aed]',
  },
  {
    id: '4',
    fullName: 'Jennifer Torres, LMFT',
    credentials: 'LMFT',
    licenseType: 'Licensed Marriage & Family Therapist',
    supervisorType: 'Approved Clinical Supervisor',
    yearsOfExperience: '11',
    city: 'Los Angeles',
    state: 'CA',
    location: 'Los Angeles, CA',
    licenseNumber: 'CA-LMFT-97321',
    licenseState: 'CA',
    formats: ['VIRTUAL', 'IN_PERSON'],
    accepting: false,
    bio: 'I specialize in couples and family systems therapy with extensive experience in cross-cultural practice. I offer a warm and reflective supervision space that supports both clinical growth and professional identity development.',
    specialties: ['Couples Therapy', 'Family Systems', 'Cultural Humility', 'Gottman Method'],
    patientPopulation: ['Adults', 'Families'],
    initials: 'JT',
    avatarColor: 'bg-[#d97706]',
  },
  {
    id: '5',
    fullName: 'Dr. Raymond Okafor, PsyD',
    credentials: 'PsyD',
    licenseType: 'Licensed Psychologist',
    supervisorType: 'Board Approved Supervisor',
    yearsOfExperience: '20',
    city: 'Houston',
    state: 'TX',
    location: 'Houston, TX',
    licenseNumber: 'TX-PSY-12083',
    licenseState: 'TX',
    formats: ['VIRTUAL'],
    accepting: true,
    bio: 'With over 20 years of experience in neuropsychological assessment and community mental health, I bring a strong developmental and systems lens to supervision. I actively support supervisees from underrepresented backgrounds in the field.',
    specialties: ['Neuropsychology', 'Assessment', 'Community Mental Health', 'Multicultural'],
    patientPopulation: ['Adults', 'Adolescents', 'Seniors'],
    initials: 'RO',
    avatarColor: 'bg-[#0891b2]',
  },
]

export const MOCK_TOTAL = 84
export const PAGE_SIZE = 10
